# Default settings to use when generating new configurations.

# Toggles the automatic adding of directories into the filesystem if they're missing. 
# Allows a user to define the directories added.
default_directories:
  enabled: true
  user_directories: []

# Adds directories that are referenced in binaries but are not in the filesystem.
add_binary_directories: true

# Adds referenced /mnt paths in shell scripts.
add_mnt_paths: true

# Adds default Linksys device models.
add_default_linksys_devices: true

# Ensures localhost is in /etc/hosts for networking purposes.
localhost_in_hosts: true

always_add:
  # Adds /etc/TZ, a standard Linux file.
  - "/etc/TZ"
  # Adds /bin/sh, which is added as a symlink to the busybox shell if it is missing from the filesystem.
  - "/bin/sh"
  # Adds /var/run/libnvram.pid. Specific to some firmware vendors and was done by prior work.
  - "/var/run/libnvram.pid"

# Deletes directories you don't want in the fs.
always_delete: 
  # Deletes /etc/securetty, a standard Linux file that restricts where users can get a shell.
  - "/etc/securetty"
  # Deletes /etc/scripts/sys_resetbutton, custom to some firmware vendors and was done by prior work.
  - "/etc/scripts/sys_resetbutton"

# Enables shim targets. 
# Allows a user to specify the shim targets.
shim_targets:
  default_targets:
    reboot: true
    halt: true
    insmod: true
    modprobe: true
    mount: true
    umount: true
    ash: true
    sh: true
    bash: true
    ssh-keygen: false
    openssl: false
  user_targets: {}

# Allows a user to define whether coverage tracking is enabled.
coverage: false

# Enables default NVRAM values. 
# Allows a user to override the defaults with alternative values.
default_nvram_values:
  enabled: true
  user_nvram_values: {}

# Configures the paths used when searching for device-specific nvram values.
nvram_config:
  default_paths: true
  user_paths: []

# Enables FirmAE hack to set NVRAM values based on the presence of specific files.
enable_firmae_hack: true

# Enables setting core.force_www by default.
set_core_force_www: true

# Allows users to customize mapping from webserver binary to command to run
webserver_mapping:
  defaults: true
  user_mapping:  {}
