#!/usr/bin/env python3
"""
End-to-end smoke test for `penguin compose`.

Stands up two minimal guests sharing one `lan` compose network. The server runs
busybox httpd serving a static marker; the client wgets it and writes the body
into its core.shared_dir. The test asserts the marker landed.

Designed to be runnable from CI without arch matrix expansion -- compose's
plumbing is arch-independent, so one arch is enough signal.

Invokes `penguin compose init` followed by `penguin compose run` — per-device
init scripts are baked into each project's config via a patch.yaml file, and
the compose.yaml itself is generated by penguin.
"""
import logging
import shutil
import subprocess
from pathlib import Path

import click
import yaml

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(name)s %(levelname)s %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("penguin.tests.compose")

TEST_DIR = Path(__file__).resolve().parent
REPO_ROOT = TEST_DIR.parents[2]
PENGUIN = REPO_ROOT / "penguin"
FS_DIR = TEST_DIR / "fs"
EMPTY_FS = TEST_DIR / "empty_fs.tar.gz"
PROJECTS = TEST_DIR / "projects"
COMPOSE_PROJECTS = TEST_DIR / "compose_projects"

MARKER = "penguin-compose-ok"

# Basic-target FS has no init binary; supply a minimal one that just waits so
# the guest stays alive while our init.d/ probe scripts do their work.
SLEEPER_INIT = """#!/igloo/utils/sh
/busybox sleep 600
"""

SERVER_INIT = f"""#!/igloo/utils/sh
# Smoke-test server: serve a one-line marker on tcp/4242.
export PATH="/igloo/utils:/igloo/boot:$PATH"
/busybox mkdir -p /tmp/www /igloo/shared
echo "{MARKER}" > /tmp/www/marker
/busybox ip link set eth0 up
/busybox ip addr add 192.168.1.1/24 dev eth0
echo "[compose-smoke srv] starting httpd" > /dev/console
(
  while :; do
    /busybox httpd -p 4242 -f -h /tmp/www > /dev/null 2>&1
    /busybox sleep 1
  done
) &
echo "started" > /igloo/shared/server_started
"""

CLIENT_INIT = """#!/igloo/utils/sh
# Smoke-test client: fetch the marker from the server.
export PATH="/igloo/utils:/igloo/boot:$PATH"
/busybox mkdir -p /igloo/shared
/busybox ip link set eth0 up
/busybox ip addr add 192.168.1.100/24 dev eth0
echo "[compose-smoke cli] starting probe" > /dev/console
(
  for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
    /busybox sleep 5
    body=$(/busybox wget -q -T 5 -O - http://192.168.1.1:4242/marker 2>/dev/null)
    rc=$?
    echo "[compose-smoke cli] try $i rc=$rc body=$body" > /dev/console
    if [ "$rc" = "0" ] && [ -n "$body" ]; then
      echo "$body" > /igloo/shared/compose_ok
      echo "[compose-smoke cli] SUCCESS try=$i" > /dev/console
      break
    fi
  done
) &
"""


def run(cmd, **kw):
    logger.info(f"$ {cmd}")
    subprocess.run(cmd, shell=True, check=True, **kw)


def stage_busybox(image: str, arch: str) -> None:
    """Pull busybox.<arch> out of the penguin image into FS_DIR/busybox."""
    if FS_DIR.exists():
        shutil.rmtree(FS_DIR)
    FS_DIR.mkdir()
    (FS_DIR / "bin").mkdir()
    cid = subprocess.check_output(
        f"docker create {image}", shell=True
    ).decode().strip()
    try:
        run(f"docker cp -L {cid}:/igloo_static/utils.bin/busybox.{arch} {FS_DIR}/busybox")
    finally:
        run(f"docker rm -v {cid}")
    run(f"tar -czf {EMPTY_FS} -C {FS_DIR} .")


def penguin_init(image: str) -> Path:
    """Bootstrap an empty project from EMPTY_FS; returns the project dir."""
    if PROJECTS.exists():
        shutil.rmtree(PROJECTS)
    run(
        f"{PENGUIN} --image {image} init {EMPTY_FS} --force",
        cwd=TEST_DIR,
    )
    return PROJECTS / "empty_fs"


def clone_project(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def pin_kernel(project: Path, kernel: str) -> None:
    cfg_path = project / "config.yaml"
    with open(cfg_path) as f:
        cfg = yaml.safe_load(f)
    cfg["core"]["kernel"] = kernel
    with open(cfg_path, "w") as f:
        yaml.safe_dump(cfg, f, sort_keys=False)


def write_project_patch(project: Path, init_script: str) -> None:
    """Drop a patch.yaml into the project that wires up /init.sh + init.d probe."""
    patch = {
        "core": {"shared_dir": "./shared"},
        "env": {"igloo_init": "/init.sh"},
        "static_files": {
            "/init.sh": {
                "type": "inline_file",
                "mode": 0o755,
                "contents": SLEEPER_INIT,
            },
            f"/igloo/init.d/zzz_smoke_{project.name}": {
                "type": "inline_file",
                "mode": 0o755,
                "contents": init_script,
            },
        },
    }
    with open(project / "patch_smoke.yaml", "w") as f:
        yaml.safe_dump(patch, f, sort_keys=False)


def latest_scaffold_dir() -> Path:
    """Resolve the newest auto-scaffolded compose_projects/<timestamp>/ dir."""
    if not COMPOSE_PROJECTS.exists():
        raise AssertionError(f"compose_projects/ not created at {COMPOSE_PROJECTS}")
    candidates = [p for p in COMPOSE_PROJECTS.iterdir() if p.is_dir()]
    if not candidates:
        raise AssertionError(f"no scaffold dirs under {COMPOSE_PROJECTS}")
    return max(candidates, key=lambda p: p.stat().st_mtime)


def dump_logs_on_failure(out_root: Path) -> None:
    for dev in ("server", "client"):
        clog = out_root / dev / "console.log"
        logger.error(f"--- {dev} console.log tail ---")
        if clog.exists():
            for line in clog.read_text(errors="replace").splitlines()[-100:]:
                logger.error(line)
        else:
            logger.error("(missing)")


def assert_marker(out_root: Path) -> None:
    marker = out_root / "client" / "shared" / "compose_ok"
    if not marker.exists():
        dump_logs_on_failure(out_root)
        raise AssertionError(f"compose marker missing: {marker}")
    body = marker.read_text().strip()
    if MARKER not in body:
        dump_logs_on_failure(out_root)
        raise AssertionError(f"marker has unexpected contents: {body!r}")
    logger.info(f"OK: client received {body!r} from server over compose network")


@click.command()
@click.option("--arch", default="armel",
              help="Guest arch for both devices (compose's plumbing is arch-independent).")
@click.option("--image", default="rehosting/penguin:latest")
@click.option("--kernel", default="4.10")
@click.option("--timeout", default=180, type=int,
              help="Per-device emulation timeout, seconds.")
def main(arch: str, image: str, kernel: str, timeout: int) -> None:
    if COMPOSE_PROJECTS.exists():
        shutil.rmtree(COMPOSE_PROJECTS)

    stage_busybox(image, arch)
    base_proj = penguin_init(image)

    server_proj = PROJECTS / "server"
    client_proj = PROJECTS / "client"
    clone_project(base_proj, server_proj)
    clone_project(base_proj, client_proj)
    pin_kernel(server_proj, kernel)
    pin_kernel(client_proj, kernel)
    write_project_patch(server_proj, SERVER_INIT)
    write_project_patch(client_proj, CLIENT_INIT)

    run(f"{PENGUIN} --image {image} compose init {server_proj} {client_proj}",
        cwd=TEST_DIR)
    scaffold_dir = latest_scaffold_dir()
    logger.info(f"Resolved scaffold dir: {scaffold_dir}")
    run(
        f"{PENGUIN} --image {image} compose run {scaffold_dir} --timeout {timeout}",
        cwd=TEST_DIR,
    )
    assert_marker(scaffold_dir / "results" / "latest")


if __name__ == "__main__":
    main()
