
# Information about each ABI
#   - `target_triple`: The target triple for the architecture
#   - `libnvram_arch_name`: The architecture name used in libnvram
#   - `default_abi`: The ABI used for the binaries in /igloo/utils
#   - `musl_arch_name`: The architecture name used in musl
#   - `m_flags`: The `-m` flags passed to the compiler to compile for this ABI.
#                (e.g. -mfloat-abi=hard)
ARCH_ABI_INFO = dict(
    armel=dict(
        target_triple="armv5-linux-musleabi",
        libnvram_arch_name="arm",
        default_abi="soft_float",
        abis=dict(
            soft_float=dict(
                musl_arch_name="arm",
                m_flags=dict(),
            ),
            hard_float=dict(
                target_triple="armv7-linux-musleabi",
                musl_arch_name="arm",
                m_flags=dict(float_abi="hard")
            ),
        ),
    ),
    aarch64=dict(
        target_triple="aarch64-linux-musl",
        libnvram_arch_name="aarch64",
        default_abi="default",
        abis=dict(
            default=dict(
                musl_arch_name="aarch64",
                m_flags=dict(),
            ),
            soft_float=dict(
                libnvram_arch_name="arm",
                target_triple="armv5-linux-musleabi",
                musl_arch_name="arm",
                m_flags=dict(),
            ),
            hard_float=dict(
                libnvram_arch_name="arm",
                target_triple="armv7-linux-musleabi",
                musl_arch_name="arm",
                m_flags=dict(float_abi="hard")
            ),
        ),
    ),
    powerpc=dict(
        target_triple="powerpc-linux-musl",
        libnvram_arch_name="ppc",
        default_abi="default",
        abis=dict(
            default=dict(
                musl_arch_name="powerpc",
                m_flags=dict(),
            ),
        ),
    ),
    powerpc64=dict(
        target_triple="powerpc64-linux-musl",
        libnvram_arch_name="ppc64",
        default_abi="default",
        abis=dict(
            default=dict(
                target_triple="powerpc-linux-musl",
                libnvram_arch_name="ppc",
                musl_arch_name="powerpc",
                m_flags=dict(),
            ),
            ppc64=dict(
                musl_arch_name="powerpc64",
                m_flags=dict(),
            ),
        ),
    ),
    powerpc64le=dict(
        target_triple="powerpc64le-linux-musl",
        libnvram_arch_name="ppc64le",
        default_abi="default",
        abis=dict(
            default=dict(
                target_triple="powerpcle-linux-musl",
                musl_arch_name="powerpc",
                m_flags=dict(),
            ),
            ppc64=dict(
                musl_arch_name="powerpc64le",
                m_flags=dict(),
            ),
        ),
    ),
    riscv64=dict(
        target_triple="riscv64-linux-musl",
        libnvram_arch_name="riscv64",
        default_abi="default",
        abis=dict(
            default=dict(
                musl_arch_name="riscv64",
                m_flags=dict(),
            ),
        ),
    ),
    mipsel=dict(
        target_triple="mipsel-linux-musl",
        libnvram_arch_name="mips",
        default_abi="o32",
        abis=dict(
            o32=dict(
                musl_arch_name="mips",
                m_flags=dict(abi="32"),
            )
        ),
    ),
    mipseb=dict(
        target_triple="mips-linux-musl",
        libnvram_arch_name="mips",
        default_abi="o32",
        abis=dict(
            o32=dict(
                musl_arch_name="mips",
                m_flags=dict(abi="32"),
            )
        ),
    ),
    mips64el=dict(
        target_triple="mips64el-linux-musl",
        libnvram_arch_name="mips",
        default_abi="n64",
        abis=dict(
            o32=dict(
                musl_arch_name="mips",
                m_flags=dict(abi="32"),
            ),
            n32=dict(
                musl_arch_name="mipsn32",
                m_flags=dict(abi="n32"),
            ),
            n64=dict(
                musl_arch_name="mips64",
                m_flags=dict(abi="64"),
            ),
        ),
    ),
    mips64eb=dict(
        target_triple="mips64-linux-musl",
        libnvram_arch_name="mips",
        default_abi="n64",
        abis=dict(
            o32=dict(
                musl_arch_name="mips",
                m_flags=dict(abi="32"),
            ),
            n32=dict(
                musl_arch_name="mipsn32",
                m_flags=dict(abi="n32"),
            ),
            n64=dict(
                musl_arch_name="mips64",
                m_flags=dict(abi="64"),
            ),
        ),
    ),
    intel64=dict(
        target_triple="x86_64-unknown-linux-musl",
        libnvram_arch_name="x86_64",
        default_abi="default",
        abis=dict(
            default=dict(
                musl_arch_name="x86_64",
                m_flags=dict()
            ),
            i386=dict(
                target_triple="i386-unknown-linux-musl",
                libnvram_arch_name="i386",
                musl_arch_name="i386",
                m_flags=dict(),
                extra_flags=["-fPIC"]
            )
        )
    ),
    loongarch64=dict(
        target_triple="loongarch64-unknown-linux-musl",
        libnvram_arch_name="loongarch64",
        default_abi="default",
        abis=dict(
            default=dict(
                musl_arch_name="loongarch64",
                m_flags=dict(),
            ),
        ),
    )
)
