"""
penguin.boot_env
================

Partitioning and delivery of penguin's boot-time guest environment.

Penguin's internal env knobs (``ROOT_SHELL``, ``igloo_init``, the ``IGLOO_*``
family, ...) are consumed only by guest *userspace* -- the ``source.d`` boot
scripts, ``/igloo/init``, and ``LD_PRELOAD`` constructors -- and only after
``igloo.ko`` has been inserted. None of them is read by the kernel or the
module at boot. So rather than smuggling them on the kernel command line (which
is capped at ``COMMAND_LINE_SIZE`` -- as low as 256B on MIPS, where it silently
truncates), we deliver them in an early-boot env blob that ``preinit.sh``
sources into PID1's environment, whence they propagate to the whole guest
process tree exactly as cmdline env did.

The kernel command line then carries only what must be there: ``root=``,
``init=``, ``panic=``, ``console=``, ``rw``, plus any *firmware-expected*
params -- user/config ``env:`` entries that a vendor init may read from
``/proc/cmdline`` (penguin can't know which, so it leaves all non-internal env
on the cmdline).

This module is intentionally dependency-light (stdlib only) so both the host
runner (:mod:`penguin.penguin_run`) and the boot-time file server
(``pyplugins/core/live_image.py``) can import it without import cycles.
"""

import shlex

# Penguin-internal env knobs that do NOT carry the igloo_/IGLOO_ namespace
# prefix. These are set by penguin's own runner/plugins and read only by our
# guest userspace, so they ride the boot env blob, not the kernel cmdline.
# (The prefixed knobs -- igloo_init, IGLOO_LTRACE, IGLOO_CGROUP_MODE,
# IGLOO_IPTABLES_BACKEND, IGLOO_EXT_MAC, IGLOO_OWN_IFACES, ... -- are matched by
# prefix in :func:`is_penguin_internal_env`, so new ones need no edit here.)
PENGUIN_INTERNAL_ENV: frozenset = frozenset({
    "ROOT_SHELL",
    "SHARED_DIR",
    "WWW",
    "CID",
    "STRACE",
    "PROJ_NAME",
    "LD_LIBRARY_PATH",
    "TERM",
})


def is_penguin_internal_env(key: str) -> bool:
    """Return True if ``key`` is a penguin-internal knob delivered via the
    boot env blob (off the kernel cmdline).

    Matches the ``igloo_``/``IGLOO_`` namespace plus the small set of
    historically un-prefixed knobs in :data:`PENGUIN_INTERNAL_ENV`.
    """
    return key in PENGUIN_INTERNAL_ENV or key.lower().startswith("igloo_")


def partition_boot_env(env: dict) -> tuple[dict, dict]:
    """Split ``conf['env']`` into ``(cmdline_env, blob_env)``.

    * ``blob_env`` -- penguin-internal knobs, delivered early in boot off the
      cmdline (see :func:`render_env_blob`).
    * ``cmdline_env`` -- everything else (firmware-expected / user params),
      which stays on the kernel command line.

    Insertion order is preserved within each bucket.
    """
    cmdline_env: dict = {}
    blob_env: dict = {}
    for key, value in env.items():
        (blob_env if is_penguin_internal_env(key) else cmdline_env)[key] = value
    return cmdline_env, blob_env


def render_env_blob(blob_env: dict) -> str:
    """Render ``blob_env`` as a POSIX-sh snippet of ``export K=V`` lines for
    ``preinit.sh`` to source.

    Values are shell-quoted. Valueless (``None``) knobs are skipped, matching
    the kernel's old behavior where a bare ``key`` cmdline token (no ``=``)
    never became an environment variable.
    """
    lines = [
        "# Auto-generated by penguin; sourced by preinit.sh.",
        "# Penguin's internal env, delivered over the portal instead of the",
        "# kernel command line (which MIPS caps at 256 bytes).",
    ]
    for key, value in blob_env.items():
        if value is None:
            continue
        lines.append(f"export {key}={shlex.quote(str(value))}")
    return "\n".join(lines) + "\n"
