"""
# Events Utils Package

This package contains utility modules for querying, filtering, and processing event data from the cleanguin database.
It provides reusable functions and CLI tools for working with execution, syscall, read, write, and file descriptor events.

## Database Expectations

All CLI commands expect to find a `plugins.db` SQLite database inside the specified results directory (default: `./results/latest/`).
This database is generated by cleanguin's event collection pipeline and contains all event data for querying.
If `plugins.db` is missing, commands will fail with an error.

## Running Commands

Commands should be run from the root of your cleanguin workspace or any directory where the `results` folder is accessible.
You can specify a different results directory using the `--results` option if your data is stored elsewhere.

## Example CLI usage

```bash
execs --procname myproc --fd 3 --filename log.txt --output results.txt
reads --procname myproc --fd 4 --filename input.txt --output reads.txt
writes --procname myproc --fd 5 --filename output.txt --output writes.txt
syscalls --procname myproc --syscall open --errors --output syscalls.txt
fds --procname myproc --fd 3 --output fds.txt
tasks --results ./results/latest --output tasks.txt
```

Each module provides command-line interfaces and helper functions for specific event types.
"""