#!/igloo/utils/sh

# key_path + algo should exist in guest fs
key_path=/igloo/keys/ssh.
key_type="rsa" # default key type

# Initialize quiet mode to off
quiet=0

LOGGER=/firmadyne/ttyS1

function finish {
  # If exit code was non-zero, print an error message
  if [ $? -ne 0 ]; then
    echo "ssh.shim: Error generating key pair. Bailing on shim and running" > $LOGGER
    echo "ssh.shim: original with args $@" > $LOGGER
    exec /igloo/utils/ssh-keygen.orig "$@"
  fi
}
trap finish EXIT

# Debugging, echo args
#echo "ssh.shim: Running ssh-keygen shim with args $@" > $LOGGER

# Parse arguments
while getopts ":qt:f:N:" opt; do
  case ${opt} in
    t )
      key_type=$OPTARG
      ;;
    f )
      file_path=$OPTARG
      ;;
    q )
      quiet=1
      ;;
    N )
      # Check if the next argument is another option or the passphrase
      # For now we don't use passphrase, but we need to identify the next arg
      case "$OPTARG" in
        -*|"")
          passphrase=""
          OPTIND=$((OPTIND - 1))
          ;;
        *)
          passphrase=$OPTARG
          ;;
      esac
      ;;
    \? )
      echo "ssh.shim: Unsupported option: -$OPTARG. Bailing on shim" > $LOGGER
      exit 1
      ;;
    : )
      echo "ssh.shim: Option: -$OPTARG requires an argument. Bailing on shim" > $LOGGER
      exit 1
      ;;
  esac
done

# Determine which precomputed key to use
case "$key_type" in
  rsa1)
    key="${key_path}rsa1"
    ;;
  rsa)
    key="${key_path}rsa"
    ;;
  dsa)
    key="${key_path}dsa"
    ;;
  ecdsa)
    key="${key_path}ecdsa"
    ;;
  ed25519)
    key="${key_path}ed25519"
    ;;
  *)
    echo "ssh.shim: Unknown key type: $key_type. Bailing on shim" > $LOGGER
    exit 1
    ;;
esac

# Copy the precomputed key to the desired location
cp "$key" "$file_path"
cp "$key.pub" "$file_path.pub"
chmod 6400 "$file_path"

# If not in quiet mode, print a success message
if [ $quiet -eq 0 ]; then
echo "Generating public/private ${key_type} key pair."
echo "Your identification has been saved in ${file_path}"
echo "Your public key has been saved in ${file_path}.pub"
echo "The key fingerprint is:"
echo "SHA256:d7t/gvxTYnrx2qChx1enB9LXUXB1kOV62M0BFXTHFtY root@localhost" # this better be ignored
echo "The key's randomart image is:"
echo "+--[ED25519 256]--+"
echo "|             .=%%|"
echo "|              +oE|"
echo "|               oo|"
echo "|               *o|"
echo "|        S . ..o B|"
echo "|         . ...*.*|"
echo "|           oo=.X.|"
echo "|           .*+*o+|"
echo "|          ..o=+*.|"
echo "+----[SHA256]-----+"

fi

# Exit with success
exit 0
