name: Release Container

on:
  push:
    branches:
      - main
jobs:
    remove-docker-tag:
      runs-on: ubuntu-latest
      if:  always()

      # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
      # (required)
      permissions:
        contents: read
        packages: write

      steps:
      - name: Remove Docker Tag
        uses: rafalkk/remove-dockertag-action@v1
        with:
          tag_name: most_recent_build
          github_token: ${{ secrets.GITHUB_TOKEN }}

    build_container:
        runs-on: ubuntu-latest

        steps:
          - name: Setup runner
            run: |
                  sudo apt-get update;
                  sudo apt-get install -yy curl jq

          - name: Get next version
            uses: reecetech/version-increment@2023.10.1
            id: version
            with:
              use_api: true
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
              username: rehosting
              password: ${{secrets.DOCKERHUB_TOKEN}}
            
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Build Docker image and push to Dockerhub
            uses: docker/build-push-action@v6.3.0
            with:
              context: .
              push: true
              cache-from: type=registry,ref=rehosting/penguin:latest
              cache-to: type=inline
              tags: rehosting/penguin:${{ github.sha }},rehosting/penguin:${{ steps.version.outputs.v-version }},rehosting/penguin:latest
          
          - name: Log in to GitHub Container Registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Push most recent release to GHCR
            run: docker tag rehosting/penguin:latest ghcr.io/rehosting/penguin:most_recent_build && docker push ghcr.io/rehosting/penguin:${{ github.sha }}

          - name: Create release
            id: create_release
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              tag_name: ${{ steps.version.outputs.v-version }}
              release_name: Release ${{ steps.version.outputs.v-version }} ${{ github.ref }}
              body: |
                Release ${{ steps.version.outputs.v-version }} @${{ github.ref }}
              draft: false
              prerelease: false