name: Ensure penguin init and test init are equivalent

on:
  pull_request:
    branches:
      - main
    paths:
      - src/resources/init.sh
      - tests/unit_tests/test_target/scripts/init.sh
      - src/resources/source.d/**

jobs:
  ensure_init_equivalence:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
        # This is evil. Put our init scripts together and make sure they are what we expect
        awk -v str="First" '$0 ~ str {found=1} !found' src/resources/init.sh > ${RUNNER_TEMP}/init.sh
        cat src/resources/source.d/* >> ${RUNNER_TEMP}/init.sh
        awk -v str="Run user" '$0 ~ str {found=1} found' src/resources/init.sh >> ${RUNNER_TEMP}/init.sh
        if ! diff -B ${RUNNER_TEMP}/init.sh tests/unit_tests/test_target/scripts/init.sh; then
          echo "You have changed init. You must also change our test init"
          echo "WARNING: This may be a breaking change. Consider updating version!"
          exit 1
        fi
