name: Ensure schema is up to date

on:
  pull_request:
    branches:
      - main
    paths:
      - src/penguin/penguin_config.py
      - .github/workflows/test_schema.yaml
      - docs/config_schema.md

jobs:
  upload_config_schema:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: pip install pydantic pyyaml
    - run: python3 src/penguin/penguin_config.py docs > config_schema.md
    # Ensure generated config_schma matches the one in the repo at docs/config_schema.md
    - run: if [ -e docs/config_schema.md ]; then diff config_schema.md docs/config_schema.md || (echo "Config schema is out of date. Please run 'python3 src/penguin/penguin_config.py docs > docs/config_schema.md && git add docs/config_schema.md' and push a commit with the updated schema." && exit 1) fi;
