name: Ensure schema is up to date

on:
  pull_request:
    branches:
      - main
    paths:
      - src/penguin/penguin_config.py
      - .github/workflows/test_schema.yaml
      - docs/config_schema.md

jobs:
  upload_config_schema:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: pip install pydantic pyyaml yamlcore
    - run: python3 src/penguin/penguin_config.py docs > schema_doc.md
    # Ensure generated schema_doc.md matches the one in the repo at docs/schema_doc.md
    - run: |
        if ! diff schema_doc.md docs/schema_doc.md; then
          echo "Config schema is out of date. Please run 'python3 src/penguin/penguin_config.py docs > docs/schema_doc.md && git add docs/schema_doc.md' and push a commit with the updated schema."
          exit 1
        fi
