name: Upload config schema to server

on:
  push:
    branches:
      - main
    paths:
      - src/penguin/penguin_config
      - .github/workflows/upload_config_schema.yaml

jobs:
  upload_config_schema:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: pip install pydantic pyyaml yamlcore
    - run: python3 src/penguin/penguin_config/gen_docs.py schema > config_schema.yaml
    - name: Upload config schema to server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: config_schema.yaml
        REMOTE_HOST: rehosti.ng
        REMOTE_USER: github
        TARGET: /var/www/igloo
